Server:
  port: 8082
agency:
  updates-allowed: true

spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: product-api-client
            client-secret: YatFUEUMp2H9q0Pq2EoUwfiA4OvKCrmW
            scope: openid
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/spring-boot-realm



global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "product-api"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["localhost:8082"]

