Server:
  port: 8082
agency:
  updates-allowed: true

spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: product-api-client
            client-secret: YatFUEUMp2H9q0Pq2EoUwfiA4OvKCrmW
            scope: openid
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/spring-boot-realm

